# Generated by Django 2.1.5 on 2019-03-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findyourfit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarlook',
            name='trendylooks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similarlooks', to='findyourfit_app.TrendyLook'),
        ),
    ]
